#!/usr/bin/env bash
# display information about the subdomain

display_info(){
	dig_line=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1)
	echo "$dig_line $2" | awk '{print "The subdomain "$6" is a "$4" record and points to "$5}'
}

if [ "$#" == 1 ]
then
	display_info "$1" "www"
	display_info "$1" "lb-01"
	display_info "$1" "web-01"
	display_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	display_info "$1" "$2"
fi
