#!/usr/bin/env bash
# custom 404 page
sudo apt -y update nginx
sudo apt -y install nginx
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_mssg.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
