#!/usr/bin/env bash
# custom 404 page
sudo echo "Ceci n'est pas une page\n" > /usr/share/nginx/html/error_mssg.html
sudo sed -i "/listen 80 default_server/a error_page 404 /error_mssg.html;" /etc/nginx/sites-available/default
sudo service nginx restart
